image: node:alpine
workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "lm-dev"'

stages:
  - build

build_prod:
  # 任务名称
  stage: build
  cache:
    key: build_prod
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build:prod
  artifacts:
    paths:
      - dist
